### ISSUE TITLE
SyntaxError when installing

### ISSUE THREAD

**Issue by dittlij** [osvenskan/sysv_ipc#14]
Hi there

I am trying to install sysv_ipc on a Raspberry Pi Z W (Raspbian Lite, Python 3) but receive a syntax error in the file prober.py (see error message below). Since I am rather new to using python and a raspberry pi, has anybody else experienced and already solved this issue?

Thanks for your help!

![grafik](https://user-images.githubusercontent.com/42038110/108736787-3997db00-7532-11eb-9976-e69e665cc7f1.png)

The corresponding code snipped in proper.py is:
``` python
with open("VERSION") as f:
        version = f.read().strip()

    d["SYSV_IPC_VERSION"] = f'"{version}"'
    d["PAGE_SIZE"] = probe_page_size()__

**Comment by osvenskan** [comment]
@dittlij it seems like you resolved your problem, which is great. It'd be helpful if you could post your solution here so others who have the same problem can benefit. Was it that you're running Python 3.5?

**Comment by dittlij** [comment]
Hi @osvenskan 

Exactly. I figured the update might be the solution but wanted to confirm it before posting here.
I had Python 3.5.4 installed. I updated it to 3.8.4 and now the installation worked.

Sorry for the trouble and thanks.

**Comment by plotti** [comment]
is there a way to install this with python 3.5?

**Comment by osvenskan** [comment]
@plotti It's not possible to install the most recent version of `sysv_ipc` (1.1.0) with Python 3.5. However, the previous version (1.0.1) is available on PyPI (https://pypi.org/project/sysv-ipc/1.0.1/) and that works fine with Python 3.5.  Version 1.1.0 only added one small feature to `ftok()` so unless that matters to you, you're fine using 1.0.1. 

Here's the change history --
http://semanchuk.com/philip/sysv_ipc/history.html#current
