### ISSUE TITLE
sysv_ipc.SharedMemory.size returns incorrect size in python

### ISSUE THREAD

**Issue by NoCodeNoBlunder** [osvenskan/sysv_ipc#17]
Hello, I am creating a shared memory segment in C++ and writing multiple integers to it.
In Python I want to read from these values, however, SharedMemory.size returns 4 even though the shm segment was created with a size of for example 8 bytes in C++.

I should mention that I got it to work just fine when using just one value per shared memory segment. Ideally, I would like to use multiple values per segment. 

I can include some code if that helps.
 Some help would be greatly appreciated!

**Comment by NoCodeNoBlunder** [comment]
I have made a mistake closing allready existing shm segments therefore I was not acctually creating new shm segments but using the old ones and therefore unable to update the size. 

My issue is thereby resolved.

**Comment by osvenskan** [comment]
Thanks for following up, @NoCodeNoBlunder!
